config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('find_fp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^whatshouldieat/', include('find_fp.whatshouldieat.urls', namespace='whatshouldieat')),
    url(r'^videos/', include('find_fp.videos.urls', namespace='videos')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

find_fp/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

find_fp/videos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.videos, name='videos'),
    # url(r'^write/$', views.write, name='write'),
    # url(r'^preview/$', views.preview, name='preview'),
    # url(r'^drafts/$', views.drafts, name='drafts'),
    url(r'^comment/$', views.comment, name='comment'),
    url(r'^tag/(?P<tag_name>.+)/$', views.tag, name='tag'),
    # url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit_video'),
    url(r'^(?P<slug>[-\w]+)/$', views.video, name='video'),
]

find_fp/whatshouldieat/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.WhereAreYouView.as_view(), name='whereareyou'),
    url(r'^hereiam/$', views.hereiam, name='hereiam'),
]

find_fp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

find_fp/videos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from find_fp.users.models import User


@python_2_unicode_compatible
class Video(models.Model):
    DRAFT = 'D'
    PUBLISHED = 'P'
    STATUS = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )
    URL = 'U'
    FILE = 'F'
    TYPE = (
        (URL, 'Url'),
        (FILE, 'File'),
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    video_type = models.CharField(max_length=1, choices=TYPE, default=FILE)
    video_file = models.FileField(null=True, blank=True, upload_to='videos/%Y/%m')
    youtube_url = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=5000)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    create_user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(blank=True, null=True)
    update_user = models.ForeignKey(User, null=True, blank=True,
                                    related_name="+")

    class Meta:
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")
        ordering = ("-create_date",)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Video, self).save(*args, **kwargs)
        else:
            self.update_date = datetime.now()
        if not self.slug:
            slug_str = "%s %s" % (self.pk, self.title.lower())
            self.slug = slugify(slug_str)
        if self.video_type == 'F':
            pass
        elif "watch?v=" in self.youtube_url:
            self.youtube_url = self.youtube_url.split('=')[1]
        elif "youtu.be" in self.youtube_url:
            self.youtube_url = self.youtube_url.split('be/')[1]
        else:
            pass
        super(Video, self).save(*args, **kwargs)

    # def get_content_as_markdown(self):
    #     return markdown.markdown(self.content, safe_mode='escape')

    def get_next(self):
        next = Video.objects.filter(status=Video.PUBLISHED, pk__gt=self.pk).order_by('pk')
        if next:
            return next.first()
        return self

    def get_prev(self):
        prev = Video.objects.filter(status=Video.PUBLISHED, pk__lt=self.pk).order_by('-pk')
        if prev:
            return prev.first()
        return self

    @staticmethod
    def get_published():
        videos = Video.objects.filter(status=Video.PUBLISHED)
        return videos

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            if tag:
                t, created = Tag.objects.get_or_create(tag=tag.lower(),
                                                       video=self)

    def get_tags(self):
        return Tag.objects.filter(video=self)

    def get_summary(self):
        if len(self.content) > 255:
            return u'{0}...'.format(self.content[:255])
        else:
            return self.content

    # def get_summary_as_markdown(self):
    #     return markdown.markdown(self.get_summary(), safe_mode='escape')

    def get_comments(self):
        return VideoComment.objects.filter(video=self).order_by('date')


@python_2_unicode_compatible
class Tag(models.Model):
    tag = models.CharField(max_length=50)
    video = models.ForeignKey(Video)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        unique_together = (('tag', 'video'),)
        index_together = [['tag', 'video'], ]

    def __str__(self):
        return self.tag

    @staticmethod
    def get_popular_tags():
        tags = Tag.objects.all()
        count = {}
        for tag in tags:
            if tag.video.status == Video.PUBLISHED:
                if tag.tag in count:
                    count[tag.tag] = count[tag.tag] + 1
                else:
                    count[tag.tag] = 1
        sorted_count = sorted(count.items(), key=lambda t: t[1], reverse=True)
        return sorted_count[:20]


@python_2_unicode_compatible
class VideoComment(models.Model):
    video = models.ForeignKey(Video)
    comment = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    parent = models.ForeignKey('VideoComment', null=True, blank=True)

    class Meta:
        verbose_name = _("Video Comment")
        verbose_name_plural = _("Video Comments")
        ordering = ("date",)

    def __str__(self):
        return u'{0} - {1}'.format(self.user.username, self.video.title)

find_fp/whatshouldieat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class WhereAreYou(models.Model):
    location = models.CharField(max_length=30)

    def __str__(self):
        return self.location

find_fp/whatshouldieat/forms.py
#-*- coding: utf-8 -*-
from django import forms

from .models import WhereAreYou


class WhereAreYouForm(forms.ModelForm):
    location = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'WHERE ARE YOU?'}))

    class Meta:
        model = WhereAreYou
        fields = ('location', )

find_fp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

find_fp/videos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest, HttpResponse
# from bootcamp.videos.forms import VideoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

from django.template.loader import render_to_string

from .models import Video, Tag, VideoComment

from serializers import CommentSerializer


def videos(request):
    all_videos = Video.get_published()
    return _videos(request, all_videos)


def _videos(request, videos):
    paginator = Paginator(videos, 12)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)
    popular_tags = Tag.get_popular_tags()
    return render(request, 'videos/videos.html', {
        'videos': videos,
        'popular_tags': popular_tags
    })


def video(request, slug):
    video = get_object_or_404(Video, slug=slug, status=Video.PUBLISHED)
    return render(request, 'videos/video.html', {'video': video})


def tag(request, tag_name):
    tags = Tag.objects.filter(tag=tag_name)
    videos = []
    for tag in tags:
        if tag.video.status == Video.PUBLISHED:
            videos.append(tag.video)
    return _videos(request, videos)


# @login_required
# def write(request):
#     if request.method == 'POST':
#         form = VideoForm(request.POST)
#         if form.is_valid():
#             video = Video()
#             video.create_user = request.user
#             video.title = form.cleaned_data.get('title')
#             video.content = form.cleaned_data.get('content')
#             status = form.cleaned_data.get('status')
#             if status in [Video.PUBLISHED, Video.DRAFT]:
#                 video.status = form.cleaned_data.get('status')
#             video.save()
#             tags = form.cleaned_data.get('tags')
#             video.create_tags(tags)
#             return redirect('/videos/')
#     else:
#         form = VideoForm()
#     return render(request, 'videos/write.html', {'form': form})
#
#
# @login_required
# def drafts(request):
#     drafts = Video.objects.filter(create_user=request.user,
#                                   status=Video.DRAFT)
#     return render(request, 'videos/drafts.html', {'drafts': drafts})
#
#
# @login_required
# def edit(request, id):
#     tags = ''
#     if id:
#         video = get_object_or_404(Video, pk=id)
#         for tag in video.get_tags():
#             tags = u'{0} {1}'.format(tags, tag.tag)
#         tags = tags.strip()
#     else:
#         video = Video(create_user=request.user)
#
#     if video.create_user.id != request.user.id:
#         return redirect('home')
#
#     if request.POST:
#         form = VideoForm(request.POST, instance=video)
#         if form.is_valid():
#             form.save()
#             return redirect('/videos/')
#     else:
#         form = VideoForm(instance=video, initial={'tags': tags})
#     return render(request, 'videos/edit.html', {'form': form})
#
#
# @login_required
# def preview(request):
#     try:
#         if request.method == 'POST':
#             content = request.POST.get('content')
#             html = 'Nothing to display :('
#             if len(content.strip()) > 0:
#                 # html = markdown.markdown(content, safe_mode='escape')
#                 html = content
#             return HttpResponse(html)
#         else:
#             return HttpResponseBadRequest()
#
#     except Exception, e:
#         return HttpResponseBadRequest()
#

# class CommentViewSet(viewsets.ModelViewSet):
#     # queryset = Comment.objects.filter(parent=None) # Don't
#     queryset = Comment.objects.all()
#
#     serializer_class = CommentSerializer
#
#     @list_route()
#     def roots(self, request):
#         queryset = Comment.objects.filter(parent=None)
#         serializer = self.get_serializer(queryset, many=True)
#         return Response(serializer.data)

# class CommentDetailAPIView(RetrieveAPIView):
#     queryset = VideoComment.objects.all()
#     serializer_class = CommentSerializer

@login_required
def comment(request):
    try:
        if request.method == 'POST':
            video_id = request.POST.get('video')
            video = Video.objects.get(pk=video_id)
            comment = request.POST.get('comment')
            comment = comment.strip()
            if len(comment) > 0:
                video_comment = VideoComment(user=request.user,
                                             video=video,
                                             comment=comment)
                video_comment.save()
            html = u''
            for comment in video.get_comments():
                html = u'{0}{1}'.format(html, render_to_string('videos/partial_video_comment.html',
                                        {'comment': {comment}}))
            return HttpResponse(html)

        else:
            return HttpResponseBadRequest()

    except Exception, e:
        return HttpResponseBadRequest()

find_fp/whatshouldieat/views.py
#-*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render, redirect
from django.views.generic.edit import FormView

from .forms import WhereAreYouForm


class WhereAreYouView(FormView):
    template_name = 'whatshouldieat/whereareyou.html'
    form_class = WhereAreYouForm
    success_url = 'whatshouldieat/hereiam'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.save()
        return super(WhereAreYouView, self).form_valid(form)


# def whereareyou(request):
#     form = WhereAreYouForm()
#     return render(request, 'whatshouldieat/whereareyou.html', {'form': form})


def hereiam(request):
    if request.method == "POST":
        form = WhereAreYouForm(request.POST)
        if form.is_valid():
            location = request.POST.get('location')
            context = {
                "location": location,
            }
            return render(request, 'whatshouldieat/hereiam.html', context)

        else:
            context = {
                "location": 'Are you on earth',
            }
            return render(request, 'whatshouldieat/hereiam.html', context)
    else:
        redirect('whatshouldieat')
# def hereiam(request):

# def results(request):
#     return render(request, 'whatshouldieat/results.html', {'hereiam': hereiam})

find_fp/templates/videos/drafts.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'videos' %}">{% trans 'Articles' %}</a></li>
    <li class="active">{% trans 'Drafts' %}</li>
  </ol>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans 'Title' %}</th>
        <th>{% trans 'Content' %}</th>
        <th>{% trans 'Tags' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for video in drafts %}
        <tr>
          <td><a href="{% url 'edit_video' video.pk %}">{{ video.title }}</a></td>
          <td>{{ video.get_summary_as_markdown|safe }}</td>
          <td>
            {% for tag in video.get_tags %}
              <span class="label label-default">{{ tag }}</span>
            {% endfor %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4" style="text-align: center">
            {% trans 'No draft to display' %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock main %}

find_fp/templates/videos/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'articles' %}">{% trans 'Articles' %}</a></li>
    <li><a href="{% url 'drafts' %}">{% trans 'Drafts' %}</a></li>
    <li class="active">{% trans 'Edit' %}</li>
  </ol>
  <form action="{% url 'edit_article' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {% if field.label == 'Content' %}
          {% include 'markdown_editor.html' with textarea='id_content' %}
        {% endif %}
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <a href="{% url 'drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock main %}

find_fp/templates/videos/partial_video.html
<article class="white-panel">
  <a class="block" href="{% url 'videos:video' video.slug %}">
  {% if video.youtube_url %}
    <img src="http://img.youtube.com/vi/{{video.youtube_url}}/0.jpg"/>
  {% endif %}
  <h4 class="title">{{ video.title }}</h4>
  <div class="info">
    <span class="date">
      <span class="glyphicon glyphicon-calendar"></span> {{ video.create_date }}
    </span>
    <span class="user">
      {{ video.create_user }}
    </span>
    <span class="comments">
      <span class="glyphicon glyphicon-comment"></span> {{ video.get_comments.count }} Comments
    </span>
  </div>
  </a>
  {% if video.get_tags %}
  <div class="tags">
    {% for tag in video.get_tags %}
    <a href="#"><span class="tag tag-pill tag-default">{{ tag }}</span></a> {% endfor %}
  </div>
  {% endif %}

</article>


<!-- <div class="Pin Summary">
    <article class="">

    </article>

</div> -->

find_fp/templates/videos/partial_video_comment.html
{% load humanize %}

<div class="comment">
  <div class="comment-text">
    <h5>
      <a href="{% url 'users:detail' comment.user.username %}">{{ comment.user.username }}</a>
      <small>{{ comment.date|naturaltime }}</small>
    </h5>
    <p>{{ comment.comment }}</p>
  </div>
</div>

find_fp/templates/videos/partial_video_comments.html
<hr> {% if not request.user.is_authenticated %}<span class="pull-right text-muted" id="sign-in-please" style="display: none"><small>Please Sign in for posting a comment :)</small></span>{% endif %}
<h4><span class="comment-count">{{ video.get_comments.count }}</span> Comments</h4>
<div class="post-comment clearfix">
  <form role="form" id="comment-form" method="post">
    {% csrf_token %}
    <input type="hidden" name="video" value="{{ video.pk }}">
    <div class="form-group clearfix">
      <textarea class="form-control" placeholder="Write a comment..." name="comment" id="comment" rows="3"></textarea>
    </div>
    {% if request.user.is_authenticated %}
    <button type="submit" class="btn btn-primary float-xs-right active">Submit</button> {% else %}
    <button type="submit" class="btn btn-primary float-xs-right disabled" id="disabled">Submit</button> {% endif %}
  </form>
</div>
<br>
<div id="comment-list">
  {% for comment in video.get_comments %}
    {% include 'videos/partial_video_comment.html' with comment=comment %}
  {% empty %}
    <div style="padding: .6em 0">Be the first one to comment!</div>
  {% endfor %}
</div>

find_fp/templates/videos/video.html
{% extends 'base.html' %} {% load static %} {% block title %}{{ video.title }}{% endblock %} {% block head %}
<link href="http://vjs.zencdn.net/5.8.8/video-js.css" rel="stylesheet">
<link href="{% static 'css/videos/comment.css' %}" rel="stylesheet">
<script src="http://popcornjs.org/code/dist/popcorn-complete.min.js"></script>

<!-- If you'd like to support IE8 -->
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</script>
{% endblock %} {% block content %}
<div class="row">
  <div class="info">
    <span class="date">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ video.create_date }}
    </span>
    <span class="user">
      {{ video.create_user.username }}
    </span>
    <span class="comments">
      <span class="glyphicon glyphicon-comment"></span>
      {{ video.get_comments.count }} Comments
    </span>
  </div>
  <div class="col-sm-12">
    <div class="embed-responsive embed-responsive-16by9">
      {% if video.video_file %}
        <video id="video" controls preload="auto">
          <source src="{{ MEDIA_URL }}{{ video.video_file }}" type='video/mp4'>
        </video>

        {% elif video.youtube_url %}
          <iframe src="https://www.youtube.com/embed/{{video.youtube_url}}?autoplay=1" frameborder="0" allowfullscreen></iframe>
        {% else %}
          <p>
            cannot find any videos :(
          </p>
        {% endif %}
      </div>
    </div>
    <div class="col-sm-12">
      <p class="video-desc">{{ video.description|linebreaksbr }}</p>
      {% if video.get_tags %}
        <div class="tags">
          {% for tag in video.get_tags %}
            <a href="#"><span class="tag tag-pill tag-default">{{ tag }}</span></a>
          {% endfor %}
        </div>
      {% endif %}
      {% include 'videos/partial_video_comments.html' with video=video %}
      <a class="btn btn-outline-primary" href="{% url 'videos:video' video.get_prev.slug %}" role="button"><span class="glyphicon glyphicon-pencil">prev :{{ video.get_prev.title }}</span></a>
      <a class="btn btn-outline-primary" href="{% url 'videos:video' video.get_next.slug %}" role="button"><span class="glyphicon glyphicon-pencil">next :{{ video.get_next.title }}</span></a>
      <a class="btn btn-outline-primary" href="{% url 'videos:videos' %}" role="button"><span class="glyphicon glyphicon-pencil">list</span></a>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script src="{% static 'js/videos/comment.js' %}"></script>
<script src="http://vjs.zencdn.net/5.8.8/video.js"></script>
{% endblock %}

find_fp/templates/videos/videos.html
{% extends 'base.html' %} {% load static %} {% block title %} Videos {% endblock %} {% block head %}
<link href="{% static 'css/videos/grid.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="search-box">
      <form class="form-inline">
        <input class="form-control" type="text" placeholder="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
  <div class="col-md-3">
    <div class="tags">
      <h4>Popular Tags</h4> {% for tag, count in popular_tags %}
      <a href="#"><span class="tag tag-pill tag-default">{{ tag }} {{ count }}</span></a> {% endfor %}
    </div>
  </div>
</div>
<div class="row">
  <div class="grid">
    {% for video in videos %}
    <article class="grid-item">
      <div class="summary">
        
        <a class="block" href="{% url 'videos:video' video.slug %}">
        {% if video.youtube_url %}
          <img src="http://img.youtube.com/vi/{{video.youtube_url}}/0.jpg"/>
        {% endif %}
        <h4 class="title">{{ video.title }}</h4>
        <div class="info">
          <span class="date">
            <i class="fa fa-calendar" aria-hidden="true"></i> {{ video.create_date }}
          </span>
          <span class="user">
            {{ video.create_user }}
          </span>
          <span class="comments">
            <i class="fa fa-comments" aria-hidden="true"></i> {{ video.get_comments.count }} Comments
          </span>
        </div>
        </a> {% if video.get_tags %}
        <div class="tags">
          {% for tag in video.get_tags %}
          <a href="#"><span class="tag tag-pill tag-default">{{ tag }}</span></a> {% endfor %}
        </div>
        {% endif %}
      </div>
    </article>
    {% empty %}
    <h4 class="no-data">There is no published video yet. <a href="{% url 'write' %}">Be the first one to publish!</a></h4> {% endfor %}
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    {% include 'paginator.html' with paginator=videos %}
  </div>
</div>
<ul class="fa-ul">
  <li><i class="fa-li fa fa-check-square"></i>List icons</li>
  <li><i class="fa-li fa fa-check-square"></i>can be used</li>
  <li><i class="fa-li fa fa-spinner fa-spin"></i>as bullets</li>
  <li><i class="fa-li fa fa-square"></i>in lists</li>
</ul>
{% endblock content %} {% block javascript %}
<script src="{% static 'js/videos/grid.js' %}"></script>
<script src="https://unpkg.com/masonry-layout@4.1.1/dist/masonry.pkgd.min.js"></script>
<script src="http://popcornjs.org/code/dist/popcorn-complete.min.js"></script>
{% endblock %}